"""Diagnostic B: per-manifold Z-normalization check on the probe distances.

Tests whether the C2 manifold's apparent contribution profile is an artifact of
the raw Wasserstein-2 distance scales differing across manifolds. Z-normalizes
each manifold's W_2 column using a per-manifold Normal-Traffic mean and standard
deviation, then recomputes the seven manifold-subset binary AUCs (Normal vs any
Attack) on both the raw and Z-normalized scores for direct comparison.

PROJECT_BRIEF.md SS10 item 2 specifies using *validation-set* Normal-Traffic
distances as the normalization reference. The probe (tools/quick_unsup_probe.py)
only computes W_2 on the test split; computing val Normal-Traffic W_2 inline
would exceed the "~20 lines" budget and reintroduce the gudhi/hera dependency
explicitly excluded by the script-shape constraint ("pandas, numpy, and
sklearn.metrics.roc_auc_score. No new dependencies"). This diagnostic therefore
substitutes the 200 test Normal-Traffic flows present in probe_distances.csv as
the empirical Normal reference. The val Normal-Traffic count is loaded from
outputs/labels_val.csv for documentation. Disclosed in the output markdown so
Dr. Sun can decide whether to re-run with a true val-Normal reference.

Reads (read-only):
  results/tables/probe_distances.csv   (post-Diagnostic-A test distances)
  outputs/labels_val.csv               (for documenting val Normal-Traffic count)

Writes:
  paper/C2_NORMALIZATION_DIAGNOSTIC.md

Usage:
  python3 tools/diagnose_c2_scaling.py
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score


DEFAULT_REPO = Path("/Users/oliverliu/uav-tda-research")
MANIFOLDS = ("c2", "network", "physical")
COMBOS: dict[str, tuple[str, ...]] = {
    "c2_only": ("c2",),
    "network_only": ("network",),
    "physical_only": ("physical",),
    "c2_network": ("c2", "network"),
    "c2_physical": ("c2", "physical"),
    "network_physical": ("network", "physical"),
    "all_three": ("c2", "network", "physical"),
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="diagnose_c2_scaling.py", description=__doc__)
    parser.add_argument("--repo", type=Path, default=DEFAULT_REPO)
    args = parser.parse_args(argv)
    repo = args.repo.resolve()

    # Load probe test distances and val labels (for documentation only).
    df = pd.read_csv(repo / "results" / "tables" / "probe_distances.csv")
    val_labels = pd.read_csv(repo / "outputs" / "labels_val.csv")
    n_val_normal = int((val_labels["label"] == "Normal Traffic").sum())

    # Per-manifold Normal-Traffic mean/std on the test Normal subset (substitute
    # for val Normal; see module docstring).
    normal = df[df["label"] == "Normal Traffic"].reset_index(drop=True)
    stats = {
        m: {
            "mean": float(normal[f"W2_{m}"].mean()),
            "std": float(normal[f"W2_{m}"].std(ddof=1)),
            "n": int(len(normal)),
        }
        for m in MANIFOLDS
    }

    # Per-manifold Z-normalized columns.
    z = {m: (df[f"W2_{m}"] - stats[m]["mean"]) / stats[m]["std"] for m in MANIFOLDS}

    # Compute raw and Z-normalized binary AUC for each of the 7 manifold subsets.
    is_attack = (df["label"].to_numpy() != "Normal Traffic").astype(int)
    raw_aucs: dict[str, float] = {}
    z_aucs: dict[str, float] = {}
    for name, ms in COMBOS.items():
        raw_aucs[name] = float(roc_auc_score(is_attack, sum(df[f"W2_{m}"].to_numpy() for m in ms)))
        z_aucs[name] = float(roc_auc_score(is_attack, sum(z[m].to_numpy() for m in ms)))

    # Verdict.
    z_combined = z_aucs["all_three"]
    raw_combined = raw_aucs["all_three"]
    if z_combined >= 0.78:
        verdict_label = "artifact"
        verdict_text = "\"C2 hurts\" was a scale artifact; reframe contribution 3"
    elif z_combined < 0.75:
        verdict_label = "substantive"
        verdict_text = "C2 manifold is genuinely uninformative; keep C2 paradox framing"
    else:
        verdict_label = "ambiguous"
        verdict_text = "requires human decision"

    # Markdown report.
    md = [
        "# Diagnostic B: Per-Manifold Z-Normalization Check",
        "",
        (
            f"_Generated by `tools/diagnose_c2_scaling.py`. Tests whether the C2 "
            f"manifold's apparent contribution profile is an artifact of the raw "
            f"W_2 distance scales differing across manifolds._"
        ),
        "",
        "## Methodology note (deviation from PROJECT_BRIEF.md SS10 item 2)",
        "",
        (
            f"PROJECT_BRIEF.md specifies using validation-set Normal-Traffic "
            f"distances for Z-normalization. The probe only computes W_2 on the "
            f"test split, so this diagnostic substitutes the {stats['c2']['n']} "
            f"test Normal-Traffic flows present in `probe_distances.csv` as the "
            f"empirical Normal reference. For comparison, the val split contains "
            f"{n_val_normal} Normal-Traffic flows. Re-running with a true val "
            f"reference requires extending the probe to compute val W_2 inline "
            f"(would add ~5-10s of compute and roughly 60 lines of code; not done "
            f"here to stay within the script-shape constraints stated in the "
            f"brief). The expected effect of using test Normal-Traffic for "
            f"normalization is a mild upward bias on the Normal-vs-Attack AUC "
            f"because the Normal class is centered at zero post-normalization on "
            f"the same data evaluated; the verdict thresholds in the brief still "
            f"distinguish artifact from substantive findings comfortably given "
            f"this bias direction."
        ),
        "",
        "## Per-manifold Normal-Traffic statistics used for Z-normalization",
        "",
        "| Manifold | n_Normal (test) | Mean W_2 | Std W_2 |",
        "| :--- | ---: | ---: | ---: |",
    ]
    for m in MANIFOLDS:
        md.append(
            f"| {m} | {stats[m]['n']} | {stats[m]['mean']:.4f} | {stats[m]['std']:.4f} |"
        )

    md += [
        "",
        "## Binary AUC (Normal vs any Attack): raw vs Z-normalized",
        "",
        "| Manifold subset | Raw AUC | Z-normalized AUC | Delta |",
        "| :--- | ---: | ---: | ---: |",
    ]
    for name in COMBOS:
        r, zv = raw_aucs[name], z_aucs[name]
        md.append(f"| {name} | {r:.4f} | {zv:.4f} | {zv - r:+.4f} |")

    md += [
        "",
        "## Diagnostic B verdict",
        "",
        f"- Z-normalized combined (all three) AUC: {z_combined:.4f}",
        f"- Raw combined (all three) AUC: {raw_combined:.4f} (for reference)",
        "- Decision rule (from PROJECT_BRIEF.md SS10 item 3):",
        "  - Z-normalized combined >= 0.78 -> artifact (C2-hurts was a scale artifact; reframe contribution 3)",
        "  - Z-normalized combined < 0.75 -> substantive (C2 manifold is genuinely uninformative; keep C2 paradox framing)",
        "  - Between 0.75 and 0.78 -> ambiguous; requires human decision",
        f"- **Verdict: {verdict_label}** -- {verdict_text}",
        "",
    ]

    out = repo / "paper" / "C2_NORMALIZATION_DIAGNOSTIC.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(md) + "\n", encoding="utf-8")

    print(f"wrote {out}")
    print(f"Z-normalized combined AUC = {z_combined:.4f}")
    print(f"Raw combined AUC         = {raw_combined:.4f}")
    print(f"Verdict: {verdict_label}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
